branch-defaults:
  dev:
    environment: udagram-image-filter-dev
    group_suffix: null
deploy:
  artifact: ./www/Archive.zip
global:
  application_name: udagram-image-filter
  branch: null
  default_ec2_keyname: udagramfreddev
  default_platform: Node.js running on 64bit Amazon Linux
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
